import { constants } from 'ethers';
export const HEADER_API_KEY = 'x-pixchain-api-key';
export const HEADER_SIGNATURE = 'x-pixchain-signature';
export const AddressZero = constants.AddressZero;
export const HashZero = constants.HashZero;
export const NegativeOne = constants.NegativeOne;
export const Zero = constants.Zero;
export const One = constants.One;
export const Two = constants.Two;
export const WeiPerEther = constants.WeiPerEther;
export const MaxUint256 = constants.MaxUint256;
export const EtherSymbol = constants.EtherSymbol;
